Repository sillsdev/web-languageforge, pull requests merged in 2022-09, with the labels that each got.

#1449 Establish resource limits of containers in k8s
  docker/deployment/app-deployment.yaml
  docker/deployment/db-deployment.yaml
  docker/deployment/lfmerge-deployment.yaml
  docker/deployment/mail-deployment.yaml
  docker/deployment/next-app-deployment.yaml
  docker/deployment/next-proxy-deployment.yaml
Labels: engineering

#1448 Remove 3 unused php dependencies
  docker/test-php/run.sh
  src/composer.json
  src/index.php
Labels: cleanup

#1408 Editor entry tests
  docker/docker-compose.yml
  test/common/TestLexProject/audio/TestAudio.mp3
  test/common/TestLexProject/pictures/IMG_0214.JPG
  test/common/TestLexProject/pictures/TestImage.png
  test/e2e/components/confirm-modal.component.ts
  test/e2e/components/notice.component.ts
  test/e2e/editor-entry.spec.ts
  test/e2e/pages/configuration.page.ts
  test/e2e/pages/editor.page.ts
  test/e2e/pages/entries-list.page.ts
  test/e2e/shared-files/FriedRiceWithPork.jpg
  test/e2e/shared-files/README.txt
  test/e2e/shared-files/TestAudio.mp3
  test/e2e/shared-files/TestImage.png
  test/e2e/utils/TestControl.php
  test/e2e/utils/testSetup.ts
Labels: E2E Testing

#1450 Interface language tests
  test/e2e/change-password.spec.ts
  test/e2e/components/page-header.component.ts
  test/e2e/interface-language.spec.ts
Labels: E2E Testing

#1457 updated name of k8s secrets
  .github/workflows/production.yml
  .github/workflows/staging.yml
Labels: engineering

#1455 Simplified make's clean targets
  docker/Makefile
  docs/DEVELOPER.md
Labels: engineering, cleanup

#1462 upgrade Playwright to 1.25.2
  package-lock.json
  package.json
  playwright.config.ts
Labels: E2E Testing

#1463 only install chromium for playwright
  .github/workflows/integrate-and-deploy.yml
  .github/workflows/pull-request.yml
  docker/Makefile
Labels: E2E Testing

#1461 Fixed bug where num of entries was being limited to 1,000 on project dashboard
  next-app/src/routes/projects/[project_code]/meta/+server.ts
  src/Api/Model/Shared/Dto/RightsHelper.php
  src/Api/Service/Sf.php
Labels: bug

#1465 Legacy app needed a little more memory based on testing in staging
  docker/deployment/app-deployment.yaml
Labels: bug, engineering

#1470 corrected missed naming refactor
  .github/workflows/integrate-and-deploy.yml
Labels: bug

#1487 Semantic domains tests
  test/e2e/pages/editor.page.ts
  test/e2e/semantic-domains.spec.ts
  test/e2e/utils/playwright-helpers.ts
Labels: engineering, testing
