Repository sillsdev/web-languageforge, pull requests merged in 2022-12, with the labels that each got.

#1633 upgraded db container to mongodb 5.0
  docker-compose.yml
  docker/deployment/db-deployment.yaml
Labels: security fix

#1639 Make label check use current labels
  .github/workflows/pull-request.yml
Labels: engineering

#1628 Audio settings
  src/Api/Model/Languageforge/Lexicon/Command/LexUploadCommands.php
  src/Api/Model/Languageforge/Lexicon/Dto/LexProjectDto.php
  src/Api/Model/Shared/ProjectModel.php
  src/Api/Service/Sf.php
  src/Site/Controller/Upload.php
  src/angular-app/bellows/shared/audio-recorder/audio-recorder.component.ts
  src/angular-app/bellows/shared/model/project.model.ts
  src/angular-app/languageforge/lexicon/editor/field/dc-audio.component.ts
  src/angular-app/languageforge/lexicon/editor/field/dc-picture.component.ts
  src/angular-app/languageforge/lexicon/new-project/non-send-receive/new-project-initial-data.component.ts
  src/angular-app/languageforge/lexicon/settings/import.component.ts
  src/angular-app/languageforge/lexicon/settings/project-settings.component.html
  src/angular-app/languageforge/lexicon/settings/project-settings.component.ts
  src/index.php
  test/app/languageforge/lexicon/shared/project-settings.page.ts
  test/e2e/project-settings.spec.ts
  test/php/model/languageforge/lexicon/command/LexUploadCommandsTest.php
Labels: feature

#1635 Add PR label reminder to template
  .github/pull_request_template.md
Labels: engineering

#1634 address deprecation warnings in GHA runs
  .github/workflows/integrate-and-deploy.yml
Labels: security fix

#1640 fixed asset versioning
  .github/workflows/integrate-and-deploy.yml
  docker-compose.yml
Labels: bug

#1630 hide comments and activity from project "observers"
  next-app/src/lib/auth/index.ts
  next-app/src/lib/data/user.ts
  next-app/src/lib/fetch/client.ts
  next-app/src/lib/fetch/server.ts
  next-app/src/routes/password/+server.ts
  next-app/src/routes/projects/[project_code]/+page.server.ts
  next-app/src/routes/projects/[project_code]/+page.svelte
  next-app/src/routes/projects/[project_code]/activities/+server.ts
  next-app/src/routes/projects/[project_code]/meta/+server.ts
Labels: security fix

#1647 removed old project-specific settings feature
  src/angular-app/bellows/apps/userprofile/user-profile-app.component.ts
Labels: bug

#1648 Upload playwright results when workflow fails
  .github/workflows/integrate-and-deploy.yml
  .github/workflows/pull-request.yml
Labels: testing

#1646 Repair audio seeking
  src/angular-app/bellows/shared/sound-player.component.ts
  test/e2e/editor-entry.spec.ts
  test/e2e/pages/editor.page.ts
Labels: bug

#1658 upgrade LFNext to newly released sveltekit 1.0
  next-app/package-lock.json
  next-app/package.json
  next-app/src/app.html
  next-app/src/lib/auth/index.ts
  next-app/src/lib/error/index.ts
  next-app/src/lib/fetch.ts
  next-app/src/lib/server/sf.ts
  next-app/src/lib/server/user.ts
  next-app/src/lib/stats/Stat.svelte
  next-app/src/routes/+layout.svelte
  next-app/src/routes/+page.svelte
  next-app/src/routes/password/+server.ts
  next-app/src/routes/password/change/+page.svelte
  next-app/src/routes/projects/[project_code]/+page.server.ts
  next-app/src/routes/projects/[project_code]/+page.svelte
  next-app/src/routes/projects/[project_code]/Activity.svelte
  next-app/src/routes/projects/[project_code]/activities/+server.ts
  next-app/src/routes/projects/[project_code]/meta/+server.ts
  next-app/svelte.config.js
Labels: security fix

#1660 Disable potentially flaky tests
  test/e2e/user-profile.spec.ts
Labels: testing

#1661 Remove old user-management code
  src/Api/Library/Shared/Communicate/Communicate.php
  src/Api/Model/Shared/Command/ProjectCommands.php
  src/Api/Model/Shared/Command/UserCommands.php
  src/Api/Model/Shared/Dto/ProjectManagementDto.php
  src/Api/Model/Shared/Dto/RightsHelper.php
  src/Api/Model/Shared/ProjectModel.php
  src/Api/Service/Sf.php
  src/Site/Controller/App.php
  src/Site/views/languageforge/container/languageforge.html.twig
  src/angular-app/bellows/apps/usermanagement/join-requests.component.html
  src/angular-app/bellows/apps/usermanagement/join-requests.component.ts
  src/angular-app/bellows/apps/usermanagement/members.component.html
  src/angular-app/bellows/apps/usermanagement/members.component.ts
  src/angular-app/bellows/apps/usermanagement/user-management-app.component.html
  src/angular-app/bellows/apps/usermanagement/user-management-app.component.ts
  src/angular-app/bellows/apps/usermanagement/user-management-app.module.ts
  src/angular-app/bellows/apps/usermanagement/user-management.scss
  src/angular-app/bellows/apps/usermanagement/usermanagement.html
  src/angular-app/bellows/core/api/api.service.ts
  src/angular-app/bellows/core/api/project.service.ts
  src/angular-app/bellows/shared/type-ahead.module.ts
  src/angular-app/main.ts
  src/sass/languageforge.scss
  test/php/library/shared/communicate/CommunicateTest.php
Labels: engineering
