Repository sillsdev/web-languageforge, pull requests merged in 2022-04, with the labels that each got.

#1364 convert signup tests from Protractor to Playwright
  src/angular-app/bellows/apps/public/signup/signup-app.component.html
  test/e2e/pages/signup.page.ts
  test/e2e/signup.spec.ts
Labels: E2E Testing

#1361 LFNext infrastructure and change password migration
  .github/workflows/build-and-publish-next.yml
  .github/workflows/integrate-and-deploy.yml
  .github/workflows/production.yml
  .github/workflows/staging.yml
  .vscode/extensions.json
  README.md
  docker/Makefile
  docker/deployment/Makefile
  docker/deployment/app-deployment.yaml
  docker/deployment/next-app-deployment.yaml
  docker/deployment/next-proxy-deployment.yaml
  docker/docker-compose.yml
  docker/next-app/Caddyfile
  docker/next-app/Dockerfile.next-app
  docker/next-app/Dockerfile.proxy
  docker/next-app/dev/Caddyfile
  docker/next-app/dev/Dockerfile
  docs/DEVELOPER.md
  docs/RELEASE.md
  next-app/.gitignore
  next-app/.npmrc
  next-app/README-Tech.md
  next-app/README.md
  next-app/jsconfig.json
  next-app/package-lock.json
  next-app/package.json
  next-app/postcss.config.cjs
  next-app/src/app.html
  next-app/src/lib/Header.svelte
  next-app/src/lib/PageHeader.svelte
  next-app/src/lib/app.css
  next-app/src/lib/error/Error.svelte
  next-app/src/lib/error/index.js
  next-app/src/lib/fetch/client.js
  next-app/src/lib/fetch/server.js
  next-app/src/lib/forms/Button.svelte
  next-app/src/lib/forms/Form.svelte
  next-app/src/lib/forms/Input.svelte
  next-app/src/lib/forms/index.js
  next-app/src/lib/progress/Progress.svelte
  next-app/src/lib/progress/index.js
  next-app/src/routes/__layout.svelte
  next-app/src/routes/index.svelte
  next-app/src/routes/password/change.svelte
  next-app/src/routes/password/changed.svelte
  next-app/src/routes/password/index.json.js
  next-app/static/.gitkeep
  next-app/svelte.config.js
  next-app/tailwind.config.cjs
Labels: good first issue, large task

#1377 Update/Add links under Help/About menu
  src/Site/views/languageforge/container/languageforge.html.twig
Labels: user observed, task

#1374 optimize for building and debugging PHP tests
  .gitignore
  docker/Makefile
  docker/test-php/Dockerfile
  docker/test-php/run.sh
Labels: engineering

#1379 Project settings tests
  src/angular-app/languageforge/lexicon/settings/project-settings.component.html
  test/e2e/example.spec.ts
  test/e2e/pages/project-settings.page.ts
  test/e2e/pages/projects.page.ts
  test/e2e/project-settings.spec.ts
  test/e2e/utils/TestControl.php
  test/e2e/utils/testSetup.ts
Labels: E2E Testing
