Repository sillsdev/web-languageforge, pull requests merged in 2023-02, with the labels that each got.

#1719 refactor password checks to client-side
  next-app/src/lib/debounce.ts
  next-app/src/lib/forms/Button.svelte
  next-app/src/lib/forms/Input.svelte
  next-app/src/routes/password/change/+page.server.ts
  next-app/src/routes/password/change/+page.svelte
Labels: engineering

#1722 Show warning message/bar in QA
  src/Site/views/shared/_global.scss
  src/Site/views/shared/container/container.html.twig
Labels: feature

#1723 migrate qa naming to staging instead
  .github/pull_request_template.md
  CONTRIBUTING.md
  docker-compose.yml
  docker/deployment/Makefile
  docker/next-app/Caddyfile
  docs/RELEASE.md
  src/Api/Model/Shared/ProjectModel.php
  src/angular-app/bellows/core/website-instances.ts
Labels: bug

#1727 Comment out catches and redirects to 'logout'
  src/Site/Controller/Redirect.php
Labels: bug

#1728 Redirect to projects and clear session project on project exceptions
  src/Api/Model/Shared/UserModel.php
  src/Site/Controller/App.php
  src/Site/Controller/Redirect.php
  src/Site/Handler/AuthenticationSuccessHandler.php
Labels: bug

#1724 Feat/mongo field usages playground
  docker/db/scripts/find-field-usages.mongodb
Labels: engineering

#1731 Update field names to be consistent with FLEx
  src/Api/Model/Languageforge/Lexicon/Config/LexConfig.php
  src/Api/Model/Languageforge/Lexicon/Config/LexConfiguration.php
  src/Api/Model/Languageforge/Lexicon/Import/LiftDecoder.php
  src/Api/Model/Languageforge/Lexicon/Import/LiftImport.php
  src/Api/Model/Languageforge/Lexicon/LexCommentFieldReference.php
  src/angular-app/bellows/apps/activity/activity-container.component.ts
  src/angular-app/bellows/core/offline/editor-data.service.ts
  src/angular-app/languageforge/lexicon/editor/field/dc-entry.component.html
  src/angular-app/languageforge/lexicon/editor/field/dc-entry.component.ts
  src/angular-app/languageforge/lexicon/editor/field/dc-sense.component.html
  src/angular-app/languageforge/lexicon/editor/field/dc-sense.component.ts
  src/angular-app/languageforge/lexicon/settings/configuration/configuration-fields.component.html
  test/e2e/tests/editor/editor.audio.spec.ts
  test/e2e/tests/editor/editor.comments.spec.ts
  test/e2e/tests/editor/editor.configuration.spec.ts
  test/e2e/tests/editor/editor.entries.spec.ts
  test/e2e/tests/editor/editor.pictures.spec.ts
  test/e2e/tests/entry-list.spec.ts
  test/e2e/tests/lexicon-new-project.spec.ts
  test/php/model/languageforge/lexicon/command/LexEntryCommandsTest.php
  test/php/model/languageforge/lexicon/command/LexOptionListCommandsTest.php
  test/php/model/languageforge/lexicon/command/LexProjectCommandsTest.php
  test/php/model/languageforge/lexicon/dto/LexBaseViewDtoTest.php
Labels: feature

#1733 Document new QA / testing workflow
  CONTRIBUTING.md
Labels: engineering
