Repository sillsdev/web-languageforge, pull requests merged in 2023-01, with the labels that each got.

#1665 eliminate GHA deprecation warnings
  .github/workflows/set-backlog-fields.yml
Labels: engineering

#1667 eliminate gha deprecation warnings
  .github/workflows/pull-request.yml
Labels: engineering

#1670 switch to using mariadb for ld-db
  docker-compose.yml
Labels: engineering

#1669 delete old src/js/lib folder
  src/js/lib/jquery-ui-1.10.3.custom.min.js
  src/js/lib/jquery-ui-1.8.23.custom.min.js
  src/js/lib/jquery.iframe-transport.js
  src/js/lib/slides.min.jquery.js
  src/js/lib/superfish/hoverIntent.js
  src/js/lib/superfish/jquery.js
  src/js/lib/superfish/superfish.js
  src/js/lib/superfish/superfish.min.js
  src/js/lib/superfish/supersubs.js
Labels: engineering

#1672 remove obsolete COPY line in ui-builder
  .prettierignore
  docker/ui-builder/Dockerfile
Labels: engineering

#1671 remove GD PHP extension from base-php
  docker/base-php/Dockerfile
Labels: engineering

#1673 build multi-arch arm64/amd64 base-php image
  .github/workflows/build-and-publish-base-php.yml
Labels: engineering

#1674 allow lf-app to run on ARM for Apple Silicon
  docker-compose.yml
Labels: engineering

#1675 Update PHP dependencies / add composer-dev container
  Makefile
  docker-compose.yml
  docker/composer-dev/Dockerfile
  src/composer.json
  src/composer.lock
Labels: engineering, dependencies

#1662 Run E2E tests in shards (chromium & firefox)
  .github/workflows/e2e-tests.yml
  .github/workflows/integrate-and-deploy.yml
  .github/workflows/pull-request.yml
  Makefile
  test/e2e/fixtures.ts
  test/e2e/global-setup.ts
  test/e2e/pages/base-page.ts
  test/e2e/pages/configuration-fields.tab.ts
  test/e2e/pages/editor.page.ts
  test/e2e/pages/entry-list.page.ts
  test/e2e/playwright.config.ts
  test/e2e/tests/__expected-screenshots__/editor/editor.pictures.spec.ts/Editor-pictures-First-picture-and-caption-is-present-1-chromium.png
  test/e2e/tests/__expected-screenshots__/editor/editor.pictures.spec.ts/Editor-pictures-First-picture-and-caption-is-present-1-firefox.png
  test/e2e/tests/editor-entry.spec.ts
  test/e2e/tests/editor/editor.audio.spec.ts
  test/e2e/tests/editor/editor.comments.spec.ts
  test/e2e/tests/editor/editor.configuration.spec.ts
  test/e2e/tests/editor/editor.entries.spec.ts
  test/e2e/tests/editor/editor.pictures.spec.ts
  test/e2e/tests/entry-list.spec.ts
  test/e2e/tests/reset-forgotten-password.spec.ts
  test/e2e/tests/user-profile.spec.ts
  test/e2e/utils/project-utils.ts
  test/e2e/utils/test-control-api.ts
  test/e2e/utils/types.ts
Labels: testing

#1676 upgrade PHPUnit to version 9.5 (latest version)
  docker-compose.yml
  src/composer.json
  src/composer.lock
  test/php/library/shared/communicate/CommunicateTest.php
  test/php/model/languageforge/lexicon/Import/LiftImportTest.php
  test/php/model/languageforge/lexicon/Import/LiftImportZipTest.php
  test/php/model/languageforge/lexicon/LexProjectModelTest.php
  test/php/model/languageforge/lexicon/command/LexUploadCommandsTest.php
  test/php/model/languageforge/lexicon/command/SendReceiveCommandsTest.php
  test/php/model/shared/commands/UserCommandsTest.php
  test/php/phpunit.xml
Labels: engineering, dependencies

#1678 Chore/1548 feat home page improvements
  src/Site/views/languageforge/theme/default/page/home/assets/css/main.css
  src/Site/views/languageforge/theme/default/page/home/images/pic01.jpg
  src/Site/views/languageforge/theme/default/page/home/images/pic02.jpg
  src/Site/views/languageforge/theme/default/page/home/images/pic03.jpg
  src/Site/views/languageforge/theme/default/page/home/index.html.twig
  test/e2e/pages/home.page.ts
  test/e2e/pages/index.ts
  test/e2e/tests/homepage.spec.ts
Labels: feature

#1680 update docs to new mongo 6.0 client
  docker/db/README.md
  docs/RELEASE.md
Labels: engineering

#1688 Bug/share with others dialog opening when it shouldnt
  src/Site/views/languageforge/container/languageforge.html.twig
  src/angular-app/languageforge/lexicon/core/lexicon-project.service.ts
  test/e2e/pages/home.page.ts
  test/e2e/pages/index.ts
  test/e2e/pages/terms-and-conditions.page.ts
  test/e2e/pages/user-profile.page.ts
  test/e2e/tests/homepage.spec.ts
  test/e2e/tests/terms-and-conditions.spec.ts
Labels: bug

#1685 enable xdebug for PHP tests
  docker-compose.yml
  docker/test-php/Dockerfile
  docs/DEVELOPER.md
Labels: testing

#1689 Rework and simplify PR template
  .github/pull_request_template.md
Labels: engineering

#1693 Share button and flaky E2E test fixes
  src/Site/views/languageforge/container/languageforge.html.twig
  src/angular-app/bellows/core/navbar.controller.ts
  src/angular-app/languageforge/lexicon/core/lexicon-project.service.ts
  test/e2e/constants.ts
  test/e2e/global-setup.ts
  test/e2e/pages/base-page.ts
  test/e2e/pages/configuration-input-systems.tab.ts
  test/e2e/pages/editor.page.ts
  test/e2e/pages/signup.page.ts
  test/e2e/pages/tabbed-page.ts
  test/e2e/playwright.config.ts
  test/e2e/tests/signup.spec.ts
Labels: bug

#1686 Use new LfMerge version with 10MB file size limit
  docker/lfmerge/Dockerfile
  src/angular-app/languageforge/lexicon/editor/field/dc-audio.component.ts
  src/angular-app/languageforge/lexicon/editor/field/dc-picture.component.ts
Labels: feature

#1694 update LFMerge to 2.0.133
  docker/lfmerge/Dockerfile
Labels: bug

#1692 Allow users to delete their Language Forge account
  next-app/src/routes/projects/[project_code]/Activity.svelte
  next-app/src/routes/projects/[project_code]/activities/+server.ts
  src/Api/Model/Shared/Command/UserCommands.php
  src/Api/Model/Shared/Dto/RightsHelper.php
  src/Api/Model/Shared/UserModel.php
  src/Api/Service/Sf.php
  src/angular-app/bellows/apps/siteadmin/site-admin-users.component.ts
  src/angular-app/bellows/apps/userprofile/user-profile-app.component.html
  src/angular-app/bellows/apps/userprofile/user-profile-app.component.ts
  src/angular-app/bellows/core/api/user.service.ts
  test/e2e/pages/user-profile.page.ts
  test/e2e/tests/user-profile.spec.ts
  test/php/model/shared/UserModelTest.php
  test/php/model/shared/commands/UserCommandsTest.php
  test/php/model/shared/dto/ActivityListDtoTest.php
Labels: feature

#1696 Upgrade to PHP 7.4
  docker-compose.yml
  docker/app/Dockerfile
  docker/test-php/Dockerfile
  src/Api/Library/Shared/Communicate/Email.php
  src/Api/Library/Shared/LanguageData.php
  src/Api/Model/Languageforge/Lexicon/Command/LexEntryCommands.php
  src/Api/Model/Languageforge/Lexicon/Command/LexEntryDecoder.php
  src/Api/Model/Languageforge/Lexicon/Command/LexProjectCommands.php
  src/Api/Model/Languageforge/Lexicon/Config/LexConfig.php
  src/Api/Model/Languageforge/Lexicon/Config/LexRoleViewConfig.php
  src/Api/Model/Languageforge/Lexicon/Dto/LexDbeDto.php
  src/Api/Model/Languageforge/Lexicon/Import/LiftDecoder.php
  src/Api/Model/Languageforge/Lexicon/Import/LiftImport.php
  src/Api/Model/Languageforge/Lexicon/LexEntryModel.php
  src/Api/Model/Languageforge/Lexicon/LexMultiText.php
  src/Api/Model/Languageforge/Lexicon/LexProjectModel.php
  src/Api/Model/Languageforge/Lexicon/LexSense.php
  src/Api/Model/Shared/Command/SessionCommands.php
  src/Api/Model/Shared/Dto/ActivityListDto.php
  src/Api/Model/Shared/Mapper/JsonDecoder.php
  src/Api/Model/Shared/Mapper/JsonEncoder.php
  src/Api/Model/Shared/Mapper/MapOf.php
  src/Api/Model/Shared/Mapper/MongoEncoder.php
  src/Api/Model/Shared/ProjectModel.php
  src/composer.json
  src/composer.lock
Labels: engineering

#1698 No 'Profile updated successfully' notice on delete
  src/angular-app/bellows/apps/userprofile/user-profile-app.component.html
Labels: bug

#1703 Show 'Account deleted' message on login screen
  src/Api/Service/Sf.php
Labels: feature

#1701 Boost SR limit to 10MB for audio conversion settings
  src/Api/Model/Languageforge/Lexicon/Command/LexUploadCommands.php
Labels: feature

#1707 Upgrade oauth2-google composer dependency
  src/composer.json
  src/composer.lock
Labels: engineering

#1705 LFNext editor components
  next-app/package-lock.json
  next-app/package.json
  next-app/src/lib/Details.svelte
  next-app/src/routes/+page.svelte
Labels: engineering

#1706 Delete User Account feature polish
  Makefile
  src/Api/Model/Shared/AccessTokenModel.php
  src/Api/Model/Shared/Command/UserCommands.php
  src/Api/Model/Shared/UserListModel.php
  src/Api/Model/Shared/UserModel.php
  src/angular-app/bellows/core/api/json-rpc.service.ts
  test/php/model/shared/dto/ActivityListDtoTest.php
Labels: feature

#1710 Fix OAuth by adding missing return type
  src/Site/OAuth/SelectAccountAuthorizationParametersTrait.php
Labels: bug

#1714 fixed sorting typo in LFNext playground
  next-app/src/routes/+page.svelte
Labels: bug

#1715 decided on better mark-up
  next-app/src/routes/+page.svelte
Labels: engineering

#1716 migrate to sveltekit action
  next-app/src/lib/forms/Form.svelte
  next-app/src/lib/forms/Input.svelte
  next-app/src/routes/+page.svelte
  next-app/src/routes/password/change/+page.server.ts
  next-app/src/routes/password/change/+page.svelte
  next-app/src/routes/password/change/+page.ts
Labels: engineering

#1718 Fix broken fields
  Makefile
  src/Api/Model/Languageforge/Lexicon/LexSense.php
  test/php/model/languageforge/lexicon/Import/LiftImportFlexTest.php
  test/php/model/languageforge/lexicon/LexSenseModelTest.php
Labels: bug
