Repository sillsdev/web-languageforge, pull requests merged in 2024-05, with the labels that each got.

#1790 Set up to run LexBox alongside LF in dev mode
  docker-compose.yml
Labels: engineering

#1810 After cloning new project, go to project when done
  src/angular-app/languageforge/lexicon/new-project/lexicon-new-project.component.ts
Labels: bug

#1808 chore: tiny documentation updates and fix docker compose version warning
  docker-compose.yml
  docs/DEVELOPER.md
Labels: engineering

#1809 Fix one failing E2E test on Firefox, skip the other one
  test/e2e/tests/editor/editor.entries.spec.ts
  test/e2e/tests/editor/editor.pictures.spec.ts
Labels: testing

#1807 Prevent sorting by '-audio' citation and lexeme forms
  src/angular-app/bellows/core/offline/editor-data.service.ts
  src/angular-app/languageforge/lexicon/editor/editor.component.ts
  test/e2e/utils/project-utils.ts
Labels: bug

#1812 Base php 7.4
  .github/workflows/build-and-publish-base-php.yml
  build.log
  docker/app/Dockerfile
  docker/base-php/Dockerfile
  docker/composer-dev/Dockerfile
  docker/test-php/Dockerfile
Labels: engineering

#1815 Get rid of symfony-exceptions.patch
  docker/app/Dockerfile
Labels: engineering

#1813 Require username and password for mongodb
  docker-compose.yml
  docker/deployment/base/app-deployment.yaml
  docker/deployment/base/lfmerge-deployment.yaml
  docker/deployment/base/secrets.yaml
  docker/lfmerge/Dockerfile
  scripts/scriptsConfig.php
  src/Api/Model/Shared/Mapper/MongoStore.php
  src/config.php
  test/php/TestConfig.php
Labels: engineering

#1818 Switch from NPM to PNPM for package management
  .github/workflows/e2e-tests.yml
  .github/workflows/integrate-and-deploy.yml
  .github/workflows/pull-request.yml
  .husky/pre-commit
  .vscode/tasks.json
  Makefile
  docker-compose.yml
  docker/app/Dockerfile
  docker/next-app/Dockerfile.next-app
  docker/next-app/dev/Dockerfile
  docker/ui-builder/Dockerfile
  docs/DEVELOPER.md
  next-app/README.md
  next-app/package-lock.json
  next-app/package.json
  next-app/pnpm-lock.yaml
  package-lock.json
  package.json
  pnpm-lock.yaml
  test/e2e/playwright.config.ts
  test/e2e/playwright_guide/playwright_cheatsheet.md
Labels: engineering

#1817 Fix "implicit any" Typescript errors to prepare for Typescript 5.5
  src/angular-app/bellows/apps/activity/activity-container.component.ts
  src/angular-app/bellows/core/breadcrumbs/breadcrumb.service.ts
  src/angular-app/bellows/core/offline/editor-data.service.ts
  src/angular-app/bellows/core/session.service.ts
  src/angular-app/bellows/shared/tabset.module.ts
  src/angular-app/languageforge/lexicon/editor/comment/lex-comments-view.component.ts
  src/angular-app/languageforge/lexicon/editor/editor.component.ts
  src/angular-app/languageforge/lexicon/editor/field/dc-text.component.ts
  src/angular-app/languageforge/lexicon/lexicon-app.component.ts
  src/angular-app/languageforge/lexicon/settings/configuration/field-unified-view.model.ts
  tsconfig.json
Labels: engineering

#1820 Update outdated GHA workflow versions
  .github/workflows/build-and-publish-base-php.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/integrate-and-deploy.yml
  .github/workflows/pull-request.yml
  .github/workflows/set-backlog-fields.yml
Labels: engineering
